import { getLitterReport } from "@/app/actions/pdf";

export default async function LitterReportPage({
  params,
}: {
  params: { id: string };
}) {
  const report = await getLitterReport(params.id);

  const { litter, mating, sire, dam } = report;

  return (
    <div className="max-w-4xl mx-auto p-8 print:p-0">
      {/* PRINT BUTTON */}
      <div className="mb-6 print:hidden">
        <button
          onClick={() => window.print()}
          className="bg-black text-white px-4 py-2 rounded"
        >
          Print / Save as PDF
        </button>
      </div>

      {/* REPORT */}
      <div className="space-y-8 print:space-y-4">
        {/* HEADER */}
        <div className="border-b pb-4">
          <h1 className="text-2xl font-bold">
            🧾 Litter Report
          </h1>
          <p className="text-sm text-gray-500">
            Litter ID: {litter.id}
          </p>
        </div>

        {/* BASIC INFO */}
        <section className="space-y-2">
          <h2 className="font-semibold">Basic Information</h2>

          <div className="text-sm">
            <p>Status: {litter.status}</p>
            <p>
              Birth Date:{" "}
              {litter.birth_date ?? "Not born yet"}
            </p>
            <p>
              Puppies Count:{" "}
              {litter.puppies_count ?? "N/A"}
            </p>
          </div>
        </section>

        {/* MATING */}
        <section className="space-y-2">
          <h2 className="font-semibold">Mating</h2>

          <div className="text-sm border p-3 rounded">
            <p>Mating ID: {mating?.id}</p>
            <p>Date: {mating?.mating_date}</p>
            <p>Method: {mating?.method}</p>
          </div>
        </section>

        {/* PARENTS */}
        <section className="grid grid-cols-2 gap-4">
          <div className="border p-3 rounded">
            <h3 className="font-semibold mb-2">Sire (Father)</h3>
            <p>Name: {sire?.name ?? "Unknown"}</p>
            <p>Breed: {sire?.breed ?? "-"}</p>
            <p>Reg: {sire?.reg_number ?? "-"}</p>
          </div>

          <div className="border p-3 rounded">
            <h3 className="font-semibold mb-2">Dam (Mother)</h3>
            <p>Name: {dam?.name ?? "Unknown"}</p>
            <p>Breed: {dam?.breed ?? "-"}</p>
            <p>Reg: {dam?.reg_number ?? "-"}</p>
          </div>
        </section>

        {/* HEALTH NOTE PLACEHOLDER */}
        <section className="border p-3 rounded">
          <h2 className="font-semibold mb-2">
            Health & Notes
          </h2>
          <p className="text-sm text-gray-600">
            No health records linked yet.
          </p>
        </section>

        {/* FOOTER */}
        <div className="text-xs text-gray-400 pt-6 border-t">
          Generated by Kennel SaaS • {new Date().toDateString()}
        </div>
      </div>

      {/* PRINT STYLES */}
      <style jsx global>{`
        @media print {
          body {
            background: white;
          }

          nav,
          header,
          footer {
            display: none !important;
          }

          button {
            display: none !important;
          }

          .print\:hidden {
            display: none !important;
          }

          .print\:p-0 {
            padding: 0 !important;
          }
        }
      `}</style>
    </div>
  );
}
